language: php

php:
- 5.4
- 5.5
- 5.6

env:
- FLOW_VERSION=2.3.*@dev

notifications:
  slack:
    secure: bA/i8N/+ImYyDOY/VcBZy63ArlTjrvpmZyfcpCHnnruzWC+0wCvMUnEkBtOfWb5P+bAr90o5SwtVKRP1qH5IJFctTHXnGcKHqrFXIMbuPbnCOg2Auz9vrH3hW5WEkTcZkmBgO1GB8nz5R/BdA7l0SddEIaheK7fBijvLmHzRbOY=

before_script:
- cd Build
- "./BeforeScriptTravis.sh"

script:
- phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Ttree.ContentInsight/Tests/Unit
- php bin/phpcs --standard=TYPO3Flow Packages/Application/Ttree.ContentInsight
