language: php

php:
- 5.5
- 5.6

before_script:
- cd Build
- "./BeforeScriptTravis.sh"

script:
- php bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Ttree.ContentInsight/Tests/Unit
- php bin/phpcs --standard=TYPO3Flow Packages/Application/Ttree.ContentInsight
