Ttree:
  ContentInsight:
    cache:
      # Enable Raw HTTP response cache
      enabled: TRUE
    crawling:
      # Limit website crawling depth
      maximumDepth: 1000
    presets:
      # Base preset, merged with all custom preset
      '*':
        inventoryConfiguration:
          skipExternalUris: FALSE
        invalidUriPatterns:
          javascript:
            pattern: '@^javascript\:void\(0\)$@'
          mailto:
            pattern: '@^mailto\:.*@'
          anchor:
            pattern: '@#.*@'
            message: 'Link to anchor'
          images:
            pattern: '@\.(jpe?g|png|gif)$@'
            message: 'Link to image'
        properties:
          pageTitle:
            enabled: TRUE
          navigationTitle:
            enabled: TRUE
      # Default preset
      'default':
        reportConfigurations:
          csv:
            enabled: TRUE
            renderType: 'Csv'
            renderTypeOptions:
              displayColumnHeaders: TRUE
            reportPath: '%FLOW_PATH_DATA%Reports/Ttree.ContentInsight'
            reportPrefix: 'content-inventory-report'
            properties:
              visited:
                label: 'Visited'
                position: 'after externalLink'
                postProcessor: 'Boolean'
              externalLink:
                label: 'External Link'
                postProcessor: 'Boolean'
              pageTitle:
                label: 'Page Title'
              statusCode:
                label: 'Status Code'
              redirectLocation:
                label: 'Redirect Location'
              redirectStatusCode:
                label: 'Redirect Status Code'
              currentUri:
                label: 'URL'
              metaDescription:
                label: 'Meta Description'
              metaKeywords:
                label: 'Meta Keywords'
              firstLevelHeaderCount:
                label: 'Main Header Count (H1)'
              firstLevelHeaderContent:
                label: 'Main Header Content (H1)'
              remark:
                label: 'Crawling Remark'
                position: 'end'
        properties:
          metaDescription:
            enabled: TRUE
          metaKeywords:
            enabled: TRUE
          firstLevelHeader:
            enabled: TRUE
