Ttree:
  ContentInsight:
    cache:
      # Enable Raw HTTP response cache
      enabled: TRUE
    crawling:
      # Limit website crawling depth
      maximumDepth: 1000
    presets:
      '*':
        properties:
          - 'page_title'
          - 'navigation_title'
      'default':
        properties:
          - 'meta_description'
          - 'meta_keywords'
          - 'first_level_header'